 # Application Configuration
app:
  name: "Task Orchestration Platform"
  version: "1.0.0"
  debug: false

# Database Configuration
database:
  host: "postgres"
  port: 5433
  user: "postgres"
  password: "password123"
  database: "task_scheduler"
  pool_size: 20
  max_overflow: 10

# Redis Configuration
redis:
  host: "redis"
  port: 6379
  db: 0
  max_connections: 20

# Worker Configuration
workers:
  count: 5
  max_queue_size: 10000
  task_timeout: 300

# Email Configuration (Update with your credentials)
email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  email: "nikhita.sathish01@gmail.com"
  password: "DavidDobrik01"  # Use app password for Gmail

# Monitoring
monitoring:
  metrics_port: 8000
  log_level: "INFO"
  structured_logging: true

# Security
security:
  api_key: "your-secret-api-key"
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"